version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./openapi_project
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    volumes:
      - ./openapi_project/:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    env_file:
          - openapi_project/.env